<a href="https://colab.research.google.com/github/amargauge26/dEEPLERSAING..TENSORFLOW_KERES/blob/main/13TF_cnn_exersice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [2]:
(X_train, y_train) , (X_test, y_test) = keras.datasets.mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [3]:
X_train = X_train / 255
X_test = X_test / 255

In [9]:
X_train = X_train.reshape(-1,28,28,1)
X_train.shape

(60000, 28, 28, 1)

In [8]:
X_test = X_test.reshape(-1,28,28,1)
X_test.shape

(10000, 28, 28, 1)

In [10]:
model = keras.Sequential([
    keras.layers.Conv2D(filters=32, kernel_size=(3, 3), activation='relu', input_shape=(28,28,1)),
    keras.layers.MaxPooling2D((2, 2)),

    #dense
    keras.layers.Flatten(),
    keras.layers.Dense(100, activation='relu'),
    keras.layers.Dense(10, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 36s 19ms/step - accuracy: 0.9055 - loss: 0.3112
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 42s 20ms/step - accuracy: 0.9826 - loss: 0.0565
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 42s 20ms/step - accuracy: 0.9900 - loss: 0.0331
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 39s 19ms/step - accuracy: 0.9931 - loss: 0.0228
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 40s 19ms/step - accuracy: 0.9953 - loss: 0.0150
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 42s 19ms/step - accuracy: 0.9963 - loss: 0.0113
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 39s 18ms/step - accuracy: 0.9972 - loss: 0.0084
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 42s 18ms/step - accuracy: 0.9987 - loss: 0.0045
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 42s 19ms/step - accuracy: 0.9983 - loss: 0.0050
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 33s 18ms/step - accuracy: 0.9992 - loss: 0.0030


In [11]:
model.evaluate(X_test,y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9804 - loss: 0.0785


[0.059479858726263046, 0.984499990940094]

In [12]:
y_pred= model.predict(X_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step


In [13]:
y_pred[0]

array([3.9774561e-05, 1.9840242e-03, 1.4173098e-02, 1.1033380e-02,
       6.2195928e-04, 1.6223450e-05, 7.8492577e-12, 1.0000000e+00,
       5.0518815e-05, 5.9302390e-04], dtype=float32)

In [14]:
y_pred_main = [ np.argmax(i) for i in y_pred]

In [15]:
y_pred_main[:6]

[7, 2, 1, 0, 4, 1]

In [16]:
y_test[:6]

array([7, 2, 1, 0, 4, 1], dtype=uint8)

In [17]:
from sklearn.metrics import classification_report ,confusion_matrix

In [18]:
print(confusion_matrix(y_test,y_pred_main))

[[ 977    0    0    0    0    0    2    1    0    0]
 [   0 1133    0    0    0    0    1    0    1    0]
 [   3    4 1012    3    1    0    0    7    2    0]
 [   0    0    2  999    0    5    0    1    2    1]
 [   0    0    0    0  977    0    2    0    0    3]
 [   1    0    0   10    0  879    2    0    0    0]
 [   9    3    0    0    4    1  937    0    4    0]
 [   0    3    5    0    1    1    0 1013    1    4]
 [   8    0    3    6    1    2    2    2  944    6]
 [   4    1    0    4   18    2    0    5    0  975]]


In [20]:
print(classification_report(y_test,y_pred_main))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       980
           1       0.99      1.00      0.99      1135
           2       0.99      0.98      0.99      1032
           3       0.98      0.99      0.98      1010
           4       0.98      0.99      0.98       982
           5       0.99      0.99      0.99       892
           6       0.99      0.98      0.98       958
           7       0.98      0.99      0.98      1028
           8       0.99      0.97      0.98       974
           9       0.99      0.97      0.98      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000

