<a href="https://colab.research.google.com/github/amargauge26/dEEPLERSAING..TENSORFLOW_KERES/blob/main/4tf_loss_cost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [5]:
def mae(y_true,y_predicted):
  total_error=0
  for yt,yp in zip(y_true,y_predicted):
     total_error += abs(yp - yt)
  print("Total error is:",total_error)
  mae = total_error/len(y_predicted)
  print("Mean absolute error is:",mae)
  return mae

In [6]:
mae(y_true,y_predicted)

Total error is: 2.5
Mean absolute error is: 0.5


0.5

In [7]:
np.mean(np.abs(y_predicted-y_true))

0.5

In [8]:
np.sum(np.abs(y_predicted-y_true))

2.5

In [9]:
epsilon = 1e-15

In [10]:
np.log([1e-15])

array([-34.53877639])

In [11]:
y_predicted

array([1, 1, 0, 0, 1])

In [12]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [14]:
y_predicted_new = [max(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[1, 1, 0.999999999999999, 0.999999999999999, 1]

In [16]:
y_predicted_new = np.array(y_predicted_new)

In [17]:
np.log(y_predicted_new)

array([ 0.00000000e+00,  0.00000000e+00, -9.99200722e-16, -9.99200722e-16,
        0.00000000e+00])

In [19]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

<ipython-input-19-83d81725cdeb>:1: RuntimeWarning: divide by zero encountered in log
  -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))


inf

In [20]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [21]:

log_loss(y_true, y_predicted)

17.2696280766844